---
- name: Install NGINX
  hosts: all
  remote_user: ansible
  private_key_file: ~/.ssh/id_yavm
  become: yes
  gather_facts: yes
  tasks:
  - name: Install NGINX
    ansible.builtin.include_role:
      name: nginx
